### ISSUE TITLE
[Talk]프로젝트 주제 정하기

### ISSUE THREAD

**Issue by sdlee130** [IamJunhaHwang/Anti-S#1]
### 프로젝트 주제 키워드: 모니터링

- 여기서 모니터링은 `관찰` 중에 원하는 값을 추출하는 것이 아닌 `이상치 탐지`에 가까움.

    - ex. 뉴스 사이트를 모니터링하면서 원하는 키워드가 나온 기사가 있을 시 알림을 주는 프로그램 (X)

현재까지 나온 의견
- 악성 댓글 모니터링
- 스미싱 피해 방지를 위한 문자 모니터링
- ...

**Comment by IamJunhaHwang** [comment]
`악성 댓글 모니터링`은 차별점을 주기 어려울 것 같은데, 아무래도 2번째 것이 더 재밌어보이고 관심이 가네.

**Comment by sdlee130** [comment]
그럼 문자 모니터링을 통한 스미싱 방지로 가죠

**Comment by IamJunhaHwang** [comment]
관련된 데이터랑 기존에 있는 프로그램들을 찾아보았는데, 데이터 부분은 `Kaggle`에 있었고 (영어 데이터임), 기존 프로그램들은 앱으로 만들어져 있음.

- 앱의 경우, 출시된지 오래된 앱이며, 문자에 포함된 사이트만 보고 판단함.

**Comment by sdlee130** [comment]
한글 데이터도 있을 수 있으니 좀 더 찾아보고 안되면 영어 데이터를 쓰는 방향으로 가도 될 거 같네요. 일단 기존 앱과 차별성은 확실하네요.

**Comment by IamJunhaHwang** [comment]
그러면 이 주제로 fix??

**Comment by sdlee130** [comment]
Good
