### ISSUE TITLE
요구사항 정의서 작성

### ISSUE THREAD

**Issue by sdlee130** [IamJunhaHwang/Anti-S#10]
요구사항 정의서 작성 중 기록할 필요가 있는 것들을 위한 이슈

**Comment by sdlee130** [comment]
기능적 요구사항에 네트워크 연결이 어느 부분에서 필요한지 쓰자

**Comment by IamJunhaHwang** [comment]
> 기능적 요구사항에 네트워크 연결이 어느 부분에서 필요한지 쓰자

1. 푸시알림

2. 공지 및 알림 사항(네트워크로 알림사항 업데이트 구현시)

3. 스미싱 의심 메시지 데이터 전송 받을 시

4. 앱관련 신고 및 건의사항 받을 시

**Comment by IamJunhaHwang** [comment]
스미싱 메시지로 최근 신고된 메시지 유형 분석 정보 제공 기능은 어떻게 생각하시나요?

**Comment by sdlee130** [comment]
> 스미싱 메시지로 최근 신고된 메시지 유형 분석 정보 제공 기능은 어떻게 생각하시나요?

기능은 좋은 거 같고 구현 방식을 실시간 업데이트로 할지 앱 업데이트와 함께 제공할 정보를 추가할지 정해야 할 거 같네요

**Comment by sdlee130** [comment]
> 스미싱 메시지로 최근 신고된 메시지 유형 분석 정보 제공 기능은 어떻게 생각하시나요?

제공하는 정보에 스미싱 피해 신고 방법이나 스미싱 예박 수칙과 같은 것들도 추가하죠

**Comment by IamJunhaHwang** [comment]
> > 스미싱 메시지로 최근 신고된 메시지 유형 분석 정보 제공 기능은 어떻게 생각하시나요?
> 
> 기능은 좋은 거 같고 구현 방식을 실시간 업데이트로 할지 앱 업데이트와 함께 제공할 정보를 추가할지 정해야 할 거 같네요

아무래도 실시간으로 업데이트가 된다면 좋을 것 같네요.

**Comment by IamJunhaHwang** [comment]
### 기능적 요구사항 중 스미싱 예방 모델에 필요한 부분

- 텍스트 전처리
  - ex. 특수문자는 어떻게 처리할 것인지 등

- 언어 모델은 어떤 것을 사용하는지

- pretrain, fine-tune을 어떻게 할 것인지 등등 모델 구성에 대한 디테일들
  - 모델이 받을 input size 설정
  - output은 어떻게 출력할지
  - 학습 데이터는 어떻게 구성하고 사용할 것인지
  - 모델에 대한 평가는 어떻게 할 것인지

- Tokenizer는 어떤 것을 사용할지
  - vocab 구성을 어떻게 해야될지

----------

#### 위와 같이 최대한 디테일하게 요구사항 정의서를 적어보면 좋을 것 같아요.

**Comment by sdlee130** [comment]
요구사항 정의서에는 모델 기능 관련만 넣으면 끝이다.

**Comment by sdlee130** [comment]
> 요구사항 정의서에는 모델 기능 관련만 넣으면 끝이다.

전처리 방법이나 예측 결과 반환 형식 같은 거를 쓰면 되려나?

**Comment by IamJunhaHwang** [comment]
> 요구사항 정의서에는 모델 기능 관련만 넣으면 끝이다.

사용자 입장에서 요구사항 정의서를 작성했을 때, 모델 구현에 관한 것을 정의해 놓는 것이 이상하다고 생각해서 교수님께 여쭤본 결과 추천하지 않는다는 답변을 받음.

**Comment by sdlee130** [comment]
> > 요구사항 정의서에는 모델 기능 관련만 넣으면 끝이다.
> 
> 
> 
> 사용자 입장에서 요구사항 정의서를 작성했을 때, 모델 구현에 관한 것을 정의해 놓는 것이 이상하다고 생각해서 교수님께 여쭤본 결과 추천하지 않는다는 답변을 받음.

그러면 요구사항 정의서에 대한 내용은 이걸로 끝내고 이슈를 닫도록 할게요.
