### ISSUE TITLE
어플 UI 관련 이슈

### ISSUE THREAD

**Issue by IamJunhaHwang** [IamJunhaHwang/Anti-S#11]
### 어플 초안

<img src="https://user-images.githubusercontent.com/46083287/196655029-8ccb5add-f335-44d2-b8d3-2ad629175bbf.png" width="50%"></img>

**Comment by IamJunhaHwang** [comment]
어플 초안에 대한 아이디어나 다른 참고할 만한 어플이 있다면 의견을 공유하도록 합시다.

**Comment by IamJunhaHwang** [comment]
UI 관련 툴 키워드 - 어도비XD, 제플린 플러그인, 머터리얼 라이브러리

- UI는 XML을 이용해 구성된다.

**Comment by sdlee130** [comment]
1. 방해금지 모드 시간을 나타내는 부분이 젤 아래로 가게 하고 나머지를 위로 올리는 방식
2. 해당 부분을 중간에 가게 하고 기록과 설정이 제일 아래로 가게 하는 방식   

둘 중 하나로 레이아웃을 바꾸는 것이 나을 것 같다.

**Comment by IamJunhaHwang** [comment]
> 1. 방해금지 모드 시간을 나타내는 부분이 젤 아래로 가게 하고 나머지를 위로 올리는 방식
> 2. 해당 부분을 중간에 가게 하고 기록과 설정이 제일 아래로 가게 하는 방식
> 
> 둘 중 하나로 레이아웃을 바꾸는 것이 나을 것 같다.

저는 2번이 나은 것 같아요.

**Comment by sdlee130** [comment]
레이아웃 초안과는 아예 다른 모습으로   
탭 버튼 형식으로 메인화면을 구성하였음.   
탭 버튼과 뷰 페이저 연동하여 구현
