### ISSUE TITLE
모델 구동 위치 관련 이슈

### ISSUE THREAD

**Issue by IamJunhaHwang** [IamJunhaHwang/Anti-S#12]
### 모델의 구동을 앱 내에서 해야되는지 앱 밖에서 해야되는지 결정하기 위한 이슈

-----------

- A. 앱 내에서 할 경우 고민

  - 앱 내에서 파이썬 코드를 구동시킬 수 있는가?
  - 앱 내에서 모델을 구동시킬 수 있는가?

- B. 앱 밖에서 할 경우 고민

  - 개인 정보에 관한 우려를 막기 위해 메시지 관련 정보를 서버로 보내는 방향은 지양해야 함.

  - 그렇다면, 서버에 모델을 구현해 놓은 후 API를 만들어 이용하게 할 수 있는가?

**Comment by IamJunhaHwang** [comment]
키워드 : torch mobile

관련 자료

- https://full-stack.tistory.com/3 

- https://hwanny-yy.tistory.com/8 

- https://wonjun.oopy.io/914c5614-b683-42a0-9171-e18c8397c56b

**Comment by sdlee130** [comment]
두 번째 방법이 일반적으로 많이 쓰이는 방법이다

**Comment by IamJunhaHwang** [comment]
개인정보 이슈를 원초적으로 막기 위해서는 첫 번째 방법이 더 좋을 것 같긴 한데, 서비스 자체가 잘 될지는 아직 모르겠다.

**Comment by IamJunhaHwang** [comment]
A의 딸림고민: 텍스트 전처리나 토크나이저는 어떻게 구동시킬 것인가?

**Comment by IamJunhaHwang** [comment]
### 최종 결정

- **A안 채택.**

  - 최대한 앱 내에서 네트워크를 사용하지 않고 이용할 수 있는 것을 목표로 함.

  - 추후 기술적 한계가 있을 시 불가피하게 B안으로 대체될 수는 있지만, 최대한 A안을 맞추기 위해 도전해보기.
