### ISSUE TITLE
10.20. 간이 회의록

### ISSUE THREAD

**Issue by IamJunhaHwang** [IamJunhaHwang/Anti-S#13]
10.20.에 진행한 간이 회의에 대한 내용을 정리하기 위한 이슈입니다.

**Comment by IamJunhaHwang** [comment]
현재 모두의 말뭉치의 `온라인 대화 말뭉치`를 신청 중인데 승인이 오래 걸리고 있음.

계획대로라면 오늘부터 모델에 사용한 데이터를 살펴보며 정리해야하는데 내일도 어떻게 될지 불확실함.

따라서, 계획을 수정해야 함.

-------

+) 모두의 말뭉치에서 반려를 한 번 당했었음. (사유: 신청사유의 개인/단체에 대한 구분이 명확하지 않음)

**Comment by sdlee130** [comment]
팀 멤버가 다 같이 신청해야 한다는 글을 반영하여 팀 멤버 두 명 전원이 신청 진행 중

**Comment by IamJunhaHwang** [comment]
중간 발표 전까지 베이스라인 모델을 만드는 것이 목표였으나, 계획을 수정해야 할 듯함.

**Comment by sdlee130** [comment]
내일(10/21)까지 신청에 대한 결과가 나오지 않는다면 스팸 데이터셋만으로 우선 데이터 전처리를 진행하기로 함.

**Comment by IamJunhaHwang** [comment]
데이터에 대한 간단한 EDA, 토크나이징 등의 전처리를 하는 방향으로 바꾸기로 함.

**Comment by IamJunhaHwang** [comment]
중간 발표에서 베이스라인모델을 발표하지 못하게 된다면 전처리 과정을 상세하게 발표하는 것이 괜찮을 것 같음.
