### ISSUE TITLE
입력 데이터 상의 url 처리

### ISSUE THREAD

**Issue by IamJunhaHwang** [IamJunhaHwang/Anti-S#16]
입력 데이터 상의 url 처리에 대한 이슈

-------

현재는 `url`에 들어가는 도메인을 키워드로 python의 `find`함수로 찾아내고 있는데 한계점이 존재한다. (ex. cbnu.ac.kr 으로도 접속됨)

이에 대한 해결 방안을 논의하고 기록하기 위한 이슈이다.

**Comment by IamJunhaHwang** [comment]
가장 단순한 방법으로는 `url` 맨 뒤에 등장하는 도메인 명들을 리스트로 미리 정해주어 추출하는 방식

**Comment by sdlee130** [comment]
`url`을 인식하는 기존 프로그램에 대해서 찾아보는 것도 도움될 거 같다

**Comment by IamJunhaHwang** [comment]
> `url`을 인식하는 기존 프로그램에 대해서 찾아보는 것도 도움될 거 같다

스마트폰 내 메시지 앱에서 `url`을 어떻게 인식하는지를 생각해보았는데 아래와 같은 것 같음. (공식 정보는 아님)

1. `.`이 등장했으며 이 `.` 앞 뒤로 영어가 등장했는가

2. 1번 조건 만족시 앞, 뒤로 각각 띄어쓰기가 나오는 곳까지를 `url`로 인식

**Comment by IamJunhaHwang** [comment]
- url 앞,뒤로 글자를 붙이면 문자 메시지 시스템에서 링크로 인식 안하는 것을 확인

**Comment by IamJunhaHwang** [comment]
## URL을 정규표현식으로 추출하기

```
(https?:\/\/)?(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)
```

위의 식으로 url을 추출할 수 있다.

<img src="https://user-images.githubusercontent.com/46083287/204129093-77210542-3ae6-4e7f-aecf-dc55f7c2e5fc.png" width="80%"></img>

#### url만 잘 추출됨.

파이썬 regex test: https://regex101.com/

**Comment by IamJunhaHwang** [comment]
## 코드

```python
url_regex = r"(https?:\/\/)?(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&\/\/=]*)"

reg = re.compile(url_regex)

train_data = ["www.naver.com", "lol.ps", "l.o.v.e", "lo.ve"]

for t in train_data:
    res = reg.search(t)
    if res==None:
        print("NONE",t)
    else:
        print("el")
```

**Comment by IamJunhaHwang** [comment]
url 인식은 정규표현식으로 하는 것으로 결정.
