### ISSUE TITLE
프로젝트 결과 보고서 초안 논의

### ISSUE THREAD

**Issue by IamJunhaHwang** [IamJunhaHwang/Anti-S#17]
프로젝트 결과 보고서 초안을 만들기 위한 이슈

--------
요구사항 정의서에서 작성했던 내용을 토대로 작성

- 프로젝트 정의
  - 풀고자 하는 문제
  
  - 필요성(이 프로젝트를 왜 해야만 하는가?)
    - 국내외 시장 현황, 설문조사 결과 등 언급
  
  - Input/Output 정의

- 개발선행기술
  - 기존 서비스의 특징 및 한계점
  - 우리와의 차별점
  
- 프로젝트 개발환경

- 개발 일정 및 역할
- 개발 목표 결과물
- 기대효과 및 발전방향

**Comment by IamJunhaHwang** [comment]
개발 목표 결과물과 개발 일정 부분은 이미 다른 이슈에 있던 자료들을 사용하면 될 것 같음.

**Comment by IamJunhaHwang** [comment]
개발 선행기술 조사 분석란에 논문이나 특허를 찾아볼 필요가 있음.

**Comment by IamJunhaHwang** [comment]
기존 제품의 경우 구글 플레이스토어에 있는 앱을 예시로 들면 좋을 듯함.

**Comment by IamJunhaHwang** [comment]
> 개발 선행기술 조사 분석란에 논문이나 특허를 찾아볼 필요가 있음.

논문의 경우 제가 프로젝트를 진행하면서 찾았었던 논문이 하나 있어서 이걸 쓰면 될 것 같아요.

**Comment by sdlee130** [comment]
> > 개발 선행기술 조사 분석란에 논문이나 특허를 찾아볼 필요가 있음.
> 
> 
> 
> 논문의 경우 제가 프로젝트를 진행하면서 찾았었던 논문이 하나 있어서 이걸 쓰면 될 것 같아요.

어떤 논문이죠?

**Comment by IamJunhaHwang** [comment]
> 



> > > 개발 선행기술 조사 분석란에 논문이나 특허를 찾아볼 필요가 있음.
> > 
> > 
> > 논문의 경우 제가 프로젝트를 진행하면서 찾았었던 논문이 하나 있어서 이걸 쓰면 될 것 같아요.
> 
> 어떤 논문이죠?

스미싱 탐지 시스템에 관한 논문이었는데  스미싱 텍스트 데이터가 부족하다는 한계가 있었어요.

**Comment by IamJunhaHwang** [comment]
### 논문 정보 

- 제목: SVM을 이용한 스미싱 탐지 방법

- url: http://www.riss.kr/search/detail/DetailView.do?p_mat_type=be54d9b8bc7cdb09&control_no=ea337059ffbefb03ffe0bdc3ef48d419&outLink=K

- 스미싱 탐지 기준

  문자 메시지를 구성하는 SMS형태와 URL의 특성, 전화번호체계, Web site 정보, 형태소 분리기, 기타의 특성을 가지고 스미싱 문자 메시지 탐지.

- 사용 데이터: 일반 SMS, 스미싱 SMS 모두 합해 **600개**

**Comment by IamJunhaHwang** [comment]
11.03 초안 작성 완료

**Comment by sdlee130** [comment]
> 11.03 초안 작성 완료

그럼 이슈를 닫도록 하겠습니다.
