### ISSUE TITLE
결과보고서 관련 회의록

### ISSUE THREAD

**Issue by sdlee130** [IamJunhaHwang/Anti-S#19]
11/07 멘토링 이후 결과보고서에 대한 회의록

**Comment by sdlee130** [comment]
사용자 메뉴얼에 대한 내용을 추가해보도록 하자

**Comment by sdlee130** [comment]
프로젝트 정의에 목적과 용도에 대한 내용을 추가하자

**Comment by sdlee130** [comment]
기대효과 및 발전방향에는 결론에 대해 쓰면 된다

**Comment by IamJunhaHwang** [comment]
알고리즘 한계 정의하기

**Comment by IamJunhaHwang** [comment]
모델 평가 방법을 잘 생각해서 정해야 함. 이를 위한 새로운 이슈를 만듦

**Comment by IamJunhaHwang** [comment]
> 알고리즘 한계 정의하기

알고리즘 관련해서, 딥러닝 + 스미싱 탐지를 위한 특정 로직의 조합으로 조금 더 높은 정확도를 이끌어 낼 수도 있다.

- ex) url이 등장했고 이 url이 많이 쓰이는(검증된) 사이트인지 아닌지 여부 파악 (yes, no, don't know)

  - 이에 대한 사이트명은 전에 찾은 kaggle 데이터셋을 이용하면 될 듯함.
  - 추가적으로 방송통신위원회, 한국인터넷진흥원 등의 정부기관 사이트를 찾아보면 좋을 듯함.
