### ISSUE TITLE
[Talk] 3주차 발표 준비

### ISSUE THREAD

**Issue by IamJunhaHwang** [IamJunhaHwang/Anti-S#2]
### 포함되어야 하는 내용

> **발표 시간 3분 엄수!**

- 문제
  - 필요성
  - Input / Output

- **해결 방법 (디테일하게)** 
- 차별성
- 예상 결과

**Comment by sdlee130** [comment]
예상 결과는 앱 화면으로 하는게 맞겠지?

**Comment by IamJunhaHwang** [comment]
> 예상 결과는 앱 화면으로 하는게 맞겠지?

모델을 만드는 것으로 끝일지, 앱으로 서비스까지 해야하는지 카페에 질문을 남겨 봐야 되겠다

**Comment by IamJunhaHwang** [comment]
> 모델을 만드는 것으로 끝일지, 앱으로 서비스까지 해야하는지 카페에 질문을 남겨 봐야 되겠다

앱까지 만들어서 서비스 하는 것을 목표로 해야된다고 답변 받음.

그러면, 앱은 안드로이드 앱으로 하고, 코틀린을 이용해서 만들어 보는걸로?

**Comment by IamJunhaHwang** [comment]
데이터를 어떤 것을 사용할건지도 ppt에 넣으면 좀 더 이해하기 쉬워질 것 같다.

일단 생각해 놓았던 방향은 kaggle의 데이터가 있으니 이걸 이용하는 방법이긴 하지만 추가로 방법을 찾아볼 필요가 있을 듯.

- 수집을 할 수 있나? 할 수 있다면 그 방법

------

- 현재 생각하고 있는 데이터 수집 전략

  `1.` kaggle의 데이터(spam dataset, top million site dataset)을 이용. [spam dataset의 경우 back translation 방법 사용]

- kaggle 링크

  - `Alexa Top 1 Million Sites` :  https://www.kaggle.com/datasets/cheedcheed/top1m
  - `SMS Spam Collection Dataset` : https://www.kaggle.com/datasets/uciml/sms-spam-collection-dataset

**Comment by sdlee130** [comment]
안드로이드 앱의 목표라면 ppt의 예상결과에도 앱 출력화면을 예상해서 만들면 되겠네요

**Comment by IamJunhaHwang** [comment]
> 안드로이드 앱의 목표라면 ppt의 예상결과에도 앱 출력화면을 예상해서 만들면 되겠네요

좋습니다

**Comment by IamJunhaHwang** [comment]
내일(15일) 들어갈 내용 같이 정리해보죠.

**Comment by IamJunhaHwang** [comment]
### 내용 정리

> 발표 시간 3분 엄수!

- 문제 : SMS 모니터링을 통한 스미싱 방지 프로그램

  - 필요성: `한국인터넷진흥원` 통계 자료에 따르면 스미싱으로 인한 피해가 매년 급증하고 있음.
  
  - **Input / Output**: SMS 모니터링을 통한 문자메시지 / 스미싱 위험 여부
  
- 해결 방법 (디테일하게)

  - 데이터: 한국어 데이터는 찾지 못함. 따라서, 영어 데이터셋을 번역해서 사용.

  - 모델: 허깅페이스 라이브러리의 언어 모델(BERT 계열) 사용.

    - 한국어 텍스트 데이터로 `pretrain`된 언어 모델과 성능 비교 후 좋은 성능을 보이는 모델 사용.

- 차별성

  - 스미싱 방지 어플리케이션의 경우, `전화번호`와 `url`을 기반으로 탐지하는데 반해, 우리가 만들 프로젝트는 텍스트 자체의 패턴을 파악하는 것으로 차별성이 있음.

- 예상 결과물

  - SMS 모니터링을 통해 스미싱 위험 여부에 대한 알림을 주는 어플리케이션.
