### ISSUE TITLE
모델 평가 방법에 대한 이슈

### ISSUE THREAD

**Issue by sdlee130** [IamJunhaHwang/Anti-S#21]
### 모델 평가 방법을 정하기 위한 이슈

  - 어떤 데이터를 사용할 것인가?

  - 평가 지표는 어떤 것을 선택하고 그 근거.
    - ex) f1score, precision, recall, accuracy 등

**Comment by IamJunhaHwang** [comment]
1. 기존 데이터에서 split 해서 사용

**Comment by sdlee130** [comment]
2. 새로운 스팸이나 스미싱 데이터셋 찾아보기

**Comment by IamJunhaHwang** [comment]
3. 기존에 존재하는 앱과 비교하기 (스미싱 문자, 정상 문자 구분)

**Comment by IamJunhaHwang** [comment]
### 모델 평가 데이터

- 새로운 데이터를 찾기 어려움. (공개된 스미싱 데이터가 많지 않으므로)

- 따라서, 기존 데이터에서 split해서 사용하는 방안을 채택

**Comment by IamJunhaHwang** [comment]
### 모델 평가 지표

- 모델 평가 지표는 `Recall`과 `F1-score`를 이용하기로 결정함.

  - 해당 모델은 스미싱 위험 가능성이 있음을 사용자에게 알려주는 것을 목표로 하므로

  - 민감성이 높아야 함. (`False Positive`는 어느 정도 허용)

**Comment by IamJunhaHwang** [comment]
모델 평가에 대해 정했으므로 이슈를 닫습니다.
