### ISSUE TITLE
스미싱 예방 방법 이슈

### ISSUE THREAD

**Issue by sdlee130** [IamJunhaHwang/Anti-S#22]
어플을 통해 제공할 스미싱 방지 방법들을 공유하는 이슈

**Comment by sdlee130** [comment]
https://forbes.tistory.com/1118   

해당 링크에는 'https://bit.ly'와 같이 sms로 단축 주소가 왔을 경우 이의 원본 주소를 알 수 있게 하는 방법에 대해 나와있음

**Comment by IamJunhaHwang** [comment]
> https://forbes.tistory.com/1118
> 
> 해당 링크에는 '[https://bit.ly'와](https://bit.ly'%EC%99%80) 같이 sms로 단축 주소가 왔을 경우 이의 원본 주소를 알 수 있게 하는 방법에 대해 나와있음

모델은 url이 아닌 텍스트 자체의 패턴을 학습하기 위한 것이므로 모델링이 아닌 어플의 추가 기능으로 넣으면 좋을 것 같네요.

**Comment by sdlee130** [comment]
해당 기능은 추후에 기회가 된다면 만들어 보도록 하죠
