### ISSUE TITLE
발명 설명서 작성에 관한 이슈

### ISSUE THREAD

**Issue by sdlee130** [IamJunhaHwang/Anti-S#23]
발명 설명서 작성 항목

1. 발명의 명칭
2. 발명의 배경
3. 발명의 내용
4. 발명의 효과
5. 주장하려는 권리
6. 발명의 용도
7. 선행기술 및 참고자료

**Comment by sdlee130** [comment]
`7` 선행기술 및 참고자료는 구글 논문 검색 혹은 특허 검색 엔진 이용하여 찾아보기

**Comment by IamJunhaHwang** [comment]
`2` 발명의 배경

- 필요성을 중점적으로 서술하기. (이 시스템이 필요한 이유, 시스템의 목적 등)

**Comment by IamJunhaHwang** [comment]
`3` 발명의 내용

- 그림을 넣는 것을 권장

- 최대한 자세하게 설명하기(이 부분은 추가 논의 필요)

**Comment by IamJunhaHwang** [comment]
### 작성 시 고려 사항

- 나의 지식재산권을 보장받기 위한 것. (최대한 자세히 서술해야 함, 1차적으로 이를 읽게되는 독자는 변리사님)

- 발명의 배경(필요성 제시, 내용 간략히 언급) ==> 발명의 내용(여기서 자세하게 서술) ==> 발명의 효과

- 주장하려는 권리(청구항)이 가장 중요. (새로운 아이디어)

- 특허관련 검색은 전용 검색 엔진을 이용하는 것을 권장
  - http://www.kipris.or.kr

**Comment by IamJunhaHwang** [comment]
### 주장하려는 권리

- **1. 딥러닝 언어 모델을 이용한 스미싱 판단 방법(문자 메시지 내용 자체를 입력으로 받음)**
  - 큰 차별점

2. 인터넷 연결 없이 스미싱을 판단하는 방법

3. 문자 메시지 상의 url 처리 방법

-----------

### 1안

#### 딥러닝 언어 모델을 이용한 스미싱 판단 방법 및 시스템

  - 딥러닝 언어 모델을 이용해 스미싱을 판단하도록 학습하는 방법
  - 문자 메시지 내용을 딥러닝 모델의 입력으로 바꾸어주는 방법
  - 문자 메시지를 수신하면 스미싱 여부를 출력해주는 방법
  - 방해 금지 모드를 이용해 on/off 할 수 있는 스미싱 방지 기능

**Comment by sdlee130** [comment]
발명의 내용   
- 1번째 시스템의 input, output을 설명
- 2번째 앱의 주요 기능 동작 과정 설명
- 3번째 추가로 구현할 기능에 대해 하나하나 설명
-

**Comment by IamJunhaHwang** [comment]
> 발명의 내용
> 
> * 1번째 시스템의 input, output을 설명
> * 2번째 앱의 주요 기능 동작 과정 설명
> * 3번째 추가로 구현할 기능에 대해 하나하나 설명

추가 구현 기능은 방해금지모드 정도만 작성하면 될듯

**Comment by IamJunhaHwang** [comment]
> > 발명의 내용
> > 
> > * 1번째 시스템의 input, output을 설명
> > * 2번째 앱의 주요 기능 동작 과정 설명
> > * 3번째 추가로 구현할 기능에 대해 하나하나 설명

- 앱의 주요 기능 동작 과정 설명에서 모델에 대해 설명해야 될 것 같네요

**Comment by IamJunhaHwang** [comment]
초안을 완성했으므로 이슈는 닫겠습니다.
