### ISSUE TITLE
12주차 발명 설명서 관련 ppt 발표 이슈

### ISSUE THREAD

**Issue by IamJunhaHwang** [IamJunhaHwang/Anti-S#24]
12주차 발명 설명서 관련 ppt 발표에 관한 이슈

내용 중 어떤 부분을 중점으로 발표할 것인지.

얼마나 자세하게 설명할 것인지.

**Comment by IamJunhaHwang** [comment]
11월 19일 발표 준비 예정

**Comment by sdlee130** [comment]
발표시간은 3~4분

**Comment by IamJunhaHwang** [comment]
`배경` ==> `선행기술` => `주장하려는 권리` ==> `발명 내용` ==> `효과`

**Comment by IamJunhaHwang** [comment]
배경과 선행기술로써 해당 시스템의 필요성 및 동기에 대해 설명한다.

**Comment by IamJunhaHwang** [comment]
주장하려는 권리를 언급한 후 이에 대해 자세하게 발명의 내용을 설명한다.

그리고 해당 시스템에 대한 발명의 효과를 설명한다.

**Comment by IamJunhaHwang** [comment]
배경 관련해서는 저번의 발표 자료를 사용해도 될 듯

**Comment by IamJunhaHwang** [comment]
발명설명서와 발표 자료에 넣을 우리 시스템의 예상 도안이 있으면 좋을듯

**Comment by IamJunhaHwang** [comment]
### 청구항에 대해 자세히 설명해야 함.
