### ISSUE TITLE
레퍼런스 저장 이슈

### ISSUE THREAD

**Issue by IamJunhaHwang** [IamJunhaHwang/Anti-S#25]
레퍼런스를 기록해놓기 위한 이슈입니다.

다양한 레퍼런스를 기록해 놓고 필요할 때 쉽게 다시 찾아 볼 수 있습니다.

- Trouble Shooting, Build 관련, IDE 관련 등등

**Comment by IamJunhaHwang** [comment]
### [안드로이드 스튜디오 그레이들(Gradle) 역할](https://uroa.tistory.com/64)

  - 안드로이드 스튜디오: 코드 에디터 역할
  - 그레이들: 코드를 빌드하는 역할

**Comment by IamJunhaHwang** [comment]
### [모델 평가](https://blog.naver.com/PostView.nhn?blogId=wideeyed&logNo=221531940245)
  - Recall, Precision, F1의 설명

+) https://gaussian37.github.io/ml-concept-ml-evaluation/

**Comment by IamJunhaHwang** [comment]
### 안드로이드 소프트웨어 스택

<img src="https://user-images.githubusercontent.com/46083287/202890279-fe3e59d8-7d04-420d-82f3-cee599734baf.png" width="50%"></img>

ref: https://developer.android.com/guide/platform?hl=ko

**Comment by IamJunhaHwang** [comment]
### 스팸 url 데이터 셋

https://www.bigdata-telecom.kr/invoke/SOKBP2603/?goodsCode=KIS0000039

**Comment by IamJunhaHwang** [comment]
### 안드로이드 이메일 보내기

https://stickode.tistory.com/287

**Comment by IamJunhaHwang** [comment]
### 문자열 리소스로 등록하기

```java
<string name="test">
코드가 아닌 리소스는
이렇게
등록해놓으면
간편하게 사용가능
</string>

textView.text = resources.getString(R.string.test)
```

**Comment by IamJunhaHwang** [comment]
### 안드로이드 스튜디오 프로젝트 폴더 구성

https://taegyuhan.github.io/android/folder_structure/

**Comment by sdlee130** [comment]
앱 개발시 사용할 수 있는 레이아웃 종류
------------------------------------------------
https://yoyo-lo.tistory.com/3

**Comment by IamJunhaHwang** [comment]
### 안드로이드 테마 컬러 값 [자주 사용]

- 검은색: #000000
- 하얀색: #FFFFFF

- 색상 코드 표: https://www.rapidtables.org/ko/web/color/RGB_Color.html

- 그림판 팔레트에서 색상 값 얻기: https://lktprogrammer.tistory.com/146

**Comment by IamJunhaHwang** [comment]
### 머터리얼 디자인 적용하기

https://congjang.medium.com/material-theme%EB%A5%BC-%ED%99%9C%EC%9A%A9%ED%95%9C-ui-%EB%94%94%EC%9E%90%EC%9D%B8-31e5365f0a1b

**Comment by IamJunhaHwang** [comment]
### Tunib-electra 관련 공식 설명

https://tunib.tistory.com/entry/TUNiB-Electra-%EA%B3%B5%EA%B0%9C

**Comment by sdlee130** [comment]
탭 레이아웃과 뷰 페이저 연동하기
https://notepad96.tistory.com/182

**Comment by IamJunhaHwang** [comment]
### 허깅페이스 모델 torchscript로 바꾸기

https://huggingface.co/docs/transformers/torchscript

**Comment by IamJunhaHwang** [comment]
### 안드로이드에 모델 올리기

https://pytorch.org/mobile/android/

https://pytorch.org/tutorials/recipes/model_preparation_android.html

https://gaussian37.github.io/dl-pytorch-deploy/

https://happy-jihye.github.io/dl/torch-2/

https://huggingface.co/docs/transformers/torchscript

https://github.com/pytorch/android-demo-app

**Comment by sdlee130** [comment]
접근 권한 설정하는 기능
-----------------------------

https://ju-hy.tistory.com/50   

코틀린으로 SMS 읽어오기
-------------------------------   

https://onedaycodeing.tistory.com/170

**Comment by IamJunhaHwang** [comment]
### SharedPreference로 데이터(문자열) 저장하기

https://youngdroidstudy.tistory.com/entry/Kotlin-%EC%BD%94%ED%8B%80%EB%A6%B0%EC%9D%98-SharedPreferences-%EB%9E%80

https://velog.io/@hyom/AndroidKotlin-SharedPreferences%EC%97%90-ArrayListObject%EB%A5%BC-%EC%A0%80%EC%9E%A5%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95

**Comment by IamJunhaHwang** [comment]
개발을 완료했으므로 해당 이슈 닫겠습니다.
