### ISSUE TITLE
안드로이드 스튜디오 협업 이슈

### ISSUE THREAD

**Issue by IamJunhaHwang** [IamJunhaHwang/Anti-S#29]
안드로이드 스튜디오 코드 관리 협업을 위한 이슈

두 개의 컴퓨터로 협업을 진행하려고 한다.

하지만, 한 쪽의 프로젝트를 다른 쪽으로 가져오면 build가 안되는 문제가 발생했다.

**Comment by IamJunhaHwang** [comment]
`settings.gradle` 문제라고도 하는데, 여전히 실행이 안된다.

**Comment by sdlee130** [comment]
프로젝트를 저장하는 파일 경로와 테스트로 실행할 에뮬레이터 버전 등을 동일하게 맞춰주는 방법으로 서로의 로컬에서 작동하는 것을 확인했음.

**Comment by IamJunhaHwang** [comment]
+) git pull을 한 후, local에서 실행하면 자동으로 gradle 파일이 바뀐다. (빌드하면서 바뀌는듯)
