### ISSUE TITLE
영어 데이터 번역 처리 관련 논의

### ISSUE THREAD

**Issue by IamJunhaHwang** [IamJunhaHwang/Anti-S#3]
## 데이터의 번역 처리

- 찾은 스팸, 스미싱 데이터 셋이 모두 영어 데이터이기 때문에 번역이 필요함.

- 따라서, 이를 어떤 식으로 번역을 할 것인지, 전처리 등을 논의하기 위한 이슈

**Comment by sdlee130** [comment]
워드, 엑셀, pdf 등의 파일을 번역해주는 그런 프로그램을 쉽게 찾을 수 있던데 그런 거 아용해서 일단 한 번 해봐야 될 듯

**Comment by sdlee130** [comment]
너무 어색하게 해석되어 있으면 다른 방법을 찾아봐야 할 듯

**Comment by IamJunhaHwang** [comment]
일단 생각하는 방식은 파파고 api를 이용하는 거였는데 일정 수준 이상으로 사용하면 과금이 된다고 하네. 이부분은 좀 더 자세히 알아봐야 될 거 같음.

어색하게 해석된 경우는 직접 수정하는 방법밖에 없을 듯

**Comment by IamJunhaHwang** [comment]
## 파파고 API  설명 공식 링크

https://developers.naver.com/docs/papago/README.md

**Comment by sdlee130** [comment]
저번에 파파고 파일 번역기 써본 후기를 알려 주세요

**Comment by IamJunhaHwang** [comment]
동음이의어나 고유명사 같은 부분은 정확하게 번역이 안되서 조정할 필요가 있어 보임.

**Comment by IamJunhaHwang** [comment]
파파고 API의 경우 하루 번역 처리 한도가 10,000자임. (케글 데이터는 36만자)

- 구글 번역 API의 경우 30일 무료로 300달러 가량을 API 요금 지원을 함.

- 파파고 API를 유료 결제하면 100만 글자 당 2만원

**Comment by IamJunhaHwang** [comment]
구글 trans 라는 비공식 라이브러리가 있다.

비공식 라이브러리인만큼 불안정하고 많이 사용하면 ip ban(?)을 당한다고 한다. 

- https://github.com/ssut/py-googletrans

**Comment by IamJunhaHwang** [comment]
EasyNMT 라는 오픈 소스를 찾았다. (API도 제공하고 있다)

https://github.com/UKPLab/EasyNMT

**Comment by sdlee130** [comment]
![image](https://user-images.githubusercontent.com/49019184/194752484-66dae1e8-9a7a-4325-8e58-de6de41e542f.png)

위의 데이터를 받아서 네이버의 파파고와 구글 번역기로 번역해 보니까 한 문자 내에서도 말투가 바뀌거나 이상하게 번역되는 등 데이터를 그대로 넣으면 학습이 되지 않을 것으로 보임. 아무래도 번역하는 거보다는 한글 데이터셋을 찾는 게 나아 보임.
