### ISSUE TITLE
발명 설명서 피드백 반영 논의

### ISSUE THREAD

**Issue by sdlee130** [IamJunhaHwang/Anti-S#32]
피드백 내용을 어떻게 반영할지에 대한 이슈

피드백 내용 1차 정리
- 기존 발명과의 차이점(학습하는 방법과 같은)
  - 청구항에 강조하면 좋다.
   
- 그림 상으로도 차별성을 볼 수 있게

**Comment by sdlee130** [comment]
차별성이 잘 드러날 수 있는 새로운 도안을 준비하면 좋을 거 같다

**Comment by IamJunhaHwang** [comment]
딥러닝 언어 모델의 학습 방법에 대해 발명 내용에 상세히 기술해야 할 것 같다.

이를 위해 학습 과정에 대해 정리할 필요가 있다.

**Comment by IamJunhaHwang** [comment]
### 기존 기술(특허)와의 차별점

기존 기술(특허): URL 기반, 딥러닝 기반

- 딥러닝 기반
  - 딥러닝을 이용해 DB를 구축해서 해당 DB와 문자 메시지를 비교해 스미싱 확률 도출하는 방식

  - 문자메시지에서 컨텐츠영역과 링크영역을 추출하고, 컨텐츠영역과 링크영역을 각각 딥러닝(deep learning) 방식으로 학습된 데이터베이스와 비교하여, 문자메시지가 스미싱 메시지에 해당할 스미싱 확률을 계산

- URL 기반
  - URL이 파일 다운로드를 지시 하는지 검출하는 방식, URL을 클라우드 브라우저로 열어보는 방식
  - **URL 검출에 의존하는 문제점**


#### 공통적인 차별점: 우리 시스템은 문자 메시지 내용 자체의 패턴을 확인한다는 점.

**Comment by IamJunhaHwang** [comment]
딥러닝 기반 특허에 대해 다시 정독해보아야겠다.

**Comment by sdlee130** [comment]
![Uploading C7944BEC-A618-4E7E-B888-4F80B4BFDF54.jpeg…]()

**Comment by sdlee130** [comment]
![93B7B153-55C4-47D1-BAC7-097DF49CBCF5](https://user-images.githubusercontent.com/49019184/203269598-e0e10f03-d16a-471e-b006-0d20f54ecc5d.jpeg)

**Comment by sdlee130** [comment]
![E5232965-B054-40DB-BD84-D90C1CFF4042](https://user-images.githubusercontent.com/49019184/203272738-8c4b99c0-8769-4e8c-bd2d-f0f631e96d98.jpeg)
