### ISSUE TITLE
Peer Review 발표 이슈

### ISSUE THREAD

**Issue by sdlee130** [IamJunhaHwang/Anti-S#35]
Peer Review 발표를 위한 PPT 작성과 대본 작성에 관한 이슈

**Comment by sdlee130** [comment]
comment 받은 word 파일에 바로 작성했던 답변을 바탕으로 ppt를 만들면 될 거 같다.

**Comment by IamJunhaHwang** [comment]
`comment`에 대해서는 발표를 위해 깔끔하게 요약해보는 것도 좋아보아요.

**Comment by IamJunhaHwang** [comment]
비슷하거나 이어서 말하기 좋은 `comment`를 묶어서 발표하기

**Comment by IamJunhaHwang** [comment]
작성한 ppt를 바탕으로 문제 없이 발표 진행해보자.
