### ISSUE TITLE
어플 아이콘 관련 이슈

### ISSUE THREAD

**Issue by sdlee130** [IamJunhaHwang/Anti-S#36]
어플 아이콘에 대한 결정을 하는 이슈

**Comment by sdlee130** [comment]
1차로 구상한 아이콘
![image](https://user-images.githubusercontent.com/49019184/204089700-f58b9bb6-a174-445e-8053-3b06941708c6.png)

**Comment by sdlee130** [comment]
앱 아이콘 설정할 때 debug repo에 저장할지 main repo에 저장할지 잘 보고 선택해야 함.   
main repo가 아닌 debug repo에 저장하면 debug 폳더를 새로 만들고 그 곳에 아이콘 이미지를 저장하게 됨.   
현재는 위 이미지의 아이콘을 main repo에 저장한 후 commit 완료한 상태임.

**Comment by IamJunhaHwang** [comment]
좋습니다. 1차는 이렇게 fix 하죠.
