### ISSUE TITLE
요구사항 정의서 멘토링 질문

### ISSUE THREAD

**Issue by sdlee130** [IamJunhaHwang/Anti-S#4]
9/26 에 진행될 멘토링에서 할 질문들에 대한 이슈

**Comment by IamJunhaHwang** [comment]
문자 모니터링 관련

- 앱으로 회원가입 시에 본인인증 메시지를 받으면 자동으로 인증번호가 들어가는 것을 보고 구현이 가능하다 생각했는데, 구현 난이도나 관련 정보가 있을까요??

**Comment by IamJunhaHwang** [comment]
요구사항정의서 작성관련해서도 물어볼 수 있는건가??

**Comment by sdlee130** [comment]
멘토에게 하는 질문은 요구사항 정의서와 관련된 것을 우선으로 하고 추가로 다른 질문을 해도 되는 걸로 기억함

**Comment by IamJunhaHwang** [comment]
그러면 요구사항 정의서 관련해서 질문할 것들을 더 생각해보자

**Comment by sdlee130** [comment]
용어 정의가 필요한 내용은 어떤 것이 있는지

**Comment by IamJunhaHwang** [comment]
요구사항 정의서에 들어갈 기능 설명은 얼마나 상세하게 작성해야 하는지

- 예를 들어, 주기능이 될 모델뿐만아니라 UI 등의 구성과 구현 방법까지 딥하게??

**Comment by sdlee130** [comment]
멘토링 시간 후에 질문에 대한 답변은 정리합시다

**Comment by IamJunhaHwang** [comment]
## 멘토링 정리

 - RFP(Request For Project, 제안요청서)를 근거로 요구사항분석서가 작성됨.

 - 요구사항분석서는 자세할수록 좋음. 하지만 자세하게 작성하려면 기술적인 지식을 먼저 갖추어야 수월함.

  -  시스템을 이용할 사용자에 대한 정의부터 시작해 디테일하게 작성하면 좋을 것 같다.

  - 요구사항분석서를 더 자세하게 작성해야 할 필요가 있다. (ex. UI 구성, 내부 동작 과정 등)

 - 요구사항 분석서는 당연하게 생각되는 것도 자세하게 작성해두어야 함. (ex. 로그아웃을 하면 로그인 창으로 이동한다.)

 - 요구사항분석서를 상세하게 작성할수록 제안 요청자나 개발자 둘 다 win-win 할 수 있음.

  - 요구사항분석서를 자세하게 작성하면 설계도 수월하게 할 수 있다. (RFP -> 요구사항분석서 -> 설계)

   - 요구사항은 기능적 요구사항 뿐만이 아니라 DB, 하드웨어 등의 요구사항도 들어간다.

 - 용어 정의는 제3자(사용자)가 보았을 때, 의미를 가늠할 수 없는 것을 위주로 작성함. (ex. 안드로이드 시스템: 제 3자는 안드로이드 시스템이 무엇인지 모를 수 있다)

===========

### 요구사항분석서를 더 자세하게 작성하기 위해 UI구성부터 빠르게 시작할 필요가 있어 보인다. 

-  팀원 모두 안드로이드 앱개발을 해본 적이 없으므로 이 부분이 약점이다.

- 따라서, 요구사항분석서도 디테일하게 작성할 수 없었다. (두루뭉술하게 적었음)

- 앱개발부터 시작해보자.
