### ISSUE TITLE
안드로이드에 모델 올리기

### ISSUE THREAD

**Issue by IamJunhaHwang** [IamJunhaHwang/Anti-S#40]
안드로이드에 모델을 올리기 위한 기록

**Comment by IamJunhaHwang** [comment]
## 자료

- Pytorch 공식 사이드: https://pytorch.org/mobile/android/

- Pytorch Github: https://github.com/pytorch/android-demo-app

- [[블로그] 오류 관련](https://asuhdevstory.tistory.com/entry/Android-Studio%EC%97%90%EC%84%9C-Pytorch-mobile%EC%9D%84-%EC%82%AC%EC%9A%A9%ED%95%98%EB%A9%B0)

**Comment by IamJunhaHwang** [comment]
안드로이드 자체에 모델을 올리는 자료도 부족하고 무엇보다 아직 **정식 버전이 아닌 데모라고 한다.**

시도는 해보되 역부족이라 생각되면 바로 서버를 이용해 API 형식으로 받는 것으로 빠르게 바꿀 필요가 있음.

@sdlee130 어떻게 생각하시나요?

**Comment by sdlee130** [comment]
최대한 시도해 보는 걸로 하시죠

**Comment by IamJunhaHwang** [comment]
### Torch Script로 바꾸는 과정이 필요

url: https://tutorials.pytorch.kr/beginner/Intro_to_TorchScript_tutorial.html

**Python 소스 코드를 직접 분석하여 TorchScript로 변환하는 스크립트 컴파일러(script compiler) 를 제공함.**

- Python 인터프리터 환경이 아니여도 작동할 수 있도록 만드는 과정임.

```python
scripted_gate = torch.jit.script(MyDecisionGate())

my_cell = MyCell(scripted_gate)
scripted_cell = torch.jit.script(my_cell)

print(scripted_gate.code)
print(scripted_cell.code)
```

<img src="https://user-images.githubusercontent.com/46083287/205429121-7b967c2f-5385-485f-99aa-42e5854f64a3.png" width="40%"></img>

**Comment by IamJunhaHwang** [comment]
## Pytorch model을 TorchScript로 변환하기

<img src="https://user-images.githubusercontent.com/46083287/205432777-98cc1fbd-194e-4edf-ace2-15e730049d12.png" width="70%"></img>

### Trace

어떤 입력값(data instance)을 사용하여 모델의 구조를 파악하고, 이 입력값의 모델 안에서의 흐름을 통해 모델을 기록하는 방식

- 조건문이 있을 경우 조건문 전체를 가져오지 못함.

- 모델의 instance를 예시 input값과 함께 torch.jit.trace 함수에 넘겨줘야 함.

```python
import torch
import torchvision

# An instance of your model.
model = torchvision.models.resnet18()

# An example input you would normally provide to your model's forward() method.
example = torch.rand(1, 3, 224, 224)

# Use torch.jit.trace to generate a torch.jit.ScriptModule via tracing.
traced_script_module = torch.jit.trace(model, example)
```

### Script

model의 instance만 input으로 넣어주면됨. [예시 input 필요 없음]

- Script의 예시는 위에 기록했음.

**Comment by IamJunhaHwang** [comment]
학습한 모델 용량: 약 300MB

**Comment by IamJunhaHwang** [comment]
토크나이저를 script형태로 바꾸지 못함. [지원 안함]

따라서, 서버를 이용해 API로 주고 받는 방향으로 가야할 것 같다.
