### ISSUE TITLE
앱 테마 디자인 이슈

### ISSUE THREAD

**Issue by sdlee130** [IamJunhaHwang/Anti-S#42]
앱 테마의 디자인을 어떻게 할지 결정하는 이슈

**Comment by sdlee130** [comment]
아이콘과 비슷하게 어두운 테마 어떠신가요? @IamJunhaHwang

**Comment by IamJunhaHwang** [comment]
> 아이콘과 비슷하게 어두운 테마 어떠신가요? @IamJunhaHwang

좋네요. 아이콘과 비슷한 컨셉으로 가면 좋을 것 같아요.

**Comment by sdlee130** [comment]
기존에 계획했던 테마로 일단 구현해냈으니 이슈는 닫도록 할게요.
