### ISSUE TITLE
Baseline 관리 1차

### ISSUE THREAD

**Issue by IamJunhaHwang** [IamJunhaHwang/Anti-S#43]
Baseline Code를 관리하기 위한 이슈입니다.

- 모델 관련 Baseline을 어떻게 설정하고 보여줄지 결정하기 위함.

**Comment by IamJunhaHwang** [comment]
## 1차 Baseline 수정 사항

- `url` 추출 관련 메소드 변경( -> 정규 표현식 기반으로한 메소드로)

- Modeling Baseline의 keyboard interrupt 내용 수정해 깔끔하게 변경하기

----------

@sdlee130 위 사항을 수정해서 바로 main에 반영하려고 합니다.

**Comment by sdlee130** [comment]
> ## 1차 Baseline 수정 사항
> 
> 
> 
> - `url` 추출 관련 메소드 변경( -> 정규 표현식 기반으로한 메소드로)
> 
> 
> 
> - Modeling Baseline의 keyboard interrupt 내용 수정해 깔끔하게 변경하기
> 
> 
> 
> ----------
> 
> 
> 
> @sdlee130 위 사항을 수정해서 바로 main에 반영하려고 합니다.

좋네요. 특히 url 추출 메소드 찾은 게 이전의 이슈도 함께 해결해낸 거라고 생각해요.

**Comment by IamJunhaHwang** [comment]
수정 완료.

**Comment by IamJunhaHwang** [comment]
추가로 Modeling Baseline에는 Test sample을 한 문장 만들어서 넣어 보았음.

**Comment by IamJunhaHwang** [comment]
수정 사항에 관한 것을 반영해서 push하였고 아직 추가해야 할 사항이 없으므로 해당 이슈는 닫겠습니다.
