### ISSUE TITLE
SMS 모니터링 범위 이슈

### ISSUE THREAD

**Issue by sdlee130** [IamJunhaHwang/Anti-S#46]
SMS 모니터링을 텍스트만 할지 송신 번호, 수신 시간까지 정하는 이슈

**Comment by sdlee130** [comment]
SMS 모니터링을 했을 때 받아올 수 있는 데이터가 문자 내용, 수신 시간, 송신자 번호가 있는데 어디까지가 필요한 데이터일까요?

**Comment by sdlee130** [comment]
일단 현재는 문자 내용까지 읽어오는 것에 성공했습니다.

**Comment by IamJunhaHwang** [comment]
> SMS 모니터링을 했을 때 받아올 수 있는 데이터가 문자 내용, 수신 시간, 송신자 번호가 있는데 어디까지가 필요한 데이터일까요?

우선적으로는 문자 내용만이 필요합니다.

**Comment by IamJunhaHwang** [comment]
추가로 그 외의 것들을 간편하게 구현 가능하다면 나중에 사용할 수도 있으니 간단하게 생각만 해두면 좋을 것 같아요.

**Comment by sdlee130** [comment]
> 추가로 그 외의 것들을 간편하게 구현 가능하다면 나중에 사용할 수도 있으니 간단하게 생각만 해두면 좋을 것 같아요.

넵. 일단 해당 내용들을 각각의 변수에 저장하는 것까지 구현하여 커밋완료 했습니다.
