### ISSUE TITLE
스팸 데이터 중복 이슈

### ISSUE THREAD

**Issue by sdlee130** [IamJunhaHwang/Anti-S#47]
스팸 데이터에 중복된 데이터가 많아 이 문제에 대한 해결책을 찾는 이슈

**Comment by sdlee130** [comment]
스팸 데이터에 unique()를 사용하여 중복된 값을 제거하고 count해보니 원래 데이터의 1/3이 되었다.

**Comment by IamJunhaHwang** [comment]
추가 데이터셋을 발견했고 문제가 되는 사항이 없음을 확인함. (라이선스 이슈)

**Comment by IamJunhaHwang** [comment]
추가 데이터 파일로 5개 정도 새로 마련하였고 스팸 데이터의 수를 기대했던 만큼 늘릴 수 있을 것 같음.

**Comment by IamJunhaHwang** [comment]
새로 찾은 데이터 파일까지 `unique()`를 진행해 중복 데이터를 지워도 문제가 없을 것으로 기대됨.

이에 대한 추가 사항이 있을 시 새로 이슈를 열기로 하고 해당 이슈는 닫음.
