### ISSUE TITLE
개발 일정

### ISSUE THREAD

**Issue by sdlee130** [IamJunhaHwang/Anti-S#5]
앞으로 개발할 내용이나 목표 기한에 대한 이슈

**Comment by sdlee130** [comment]
결국에 앱을 만드는 거긴 하지만 우선 스미싱을 감지하는 모델을 먼저 개발하는 쪽이 좋아보이는데 어떤가요?

**Comment by IamJunhaHwang** [comment]
아직 우리 둘 다 앱개발 경험이 없으니 각자 앱에 대해 공부를 하고 있기로 하고, 모델 개발에 먼저 착수하는게 좋겠네요.

**Comment by IamJunhaHwang** [comment]
우선 찾아본 데이터들이 모두 영어 데이터이니 이를 한국어로 바꾸는 작업 먼저 시작하는게 좋을 것 같네요.

일단 제가 파파고 api를 사용해서 한국어로 바꾸는게 가능한지 살펴보고 #3 에 기록할게요.

---------

데이터 링크: https://www.kaggle.com/datasets/uciml/sms-spam-collection-dataset

**Comment by IamJunhaHwang** [comment]
파파고 api의 경우 하루 번역 제한이 있어서 이를 초과하여 사용하려면 과금이 됩니다.

+) 한국어 스팸 데이터를 찾았으니 스팸이 아닌 문자 대화 데이터를 찾아 이 두 데이터를 이용해 모델을 구현하는 방향으로 가보는게 좋을 것 같네요.

**Comment by IamJunhaHwang** [comment]
18일(화) 16:00 ~ 18:00, 19일(수) 13:00 ~ 16:00: 요구사항 정의서 완성

20일(목) 10:00 ~ 13:00, 21일(금) 10:00 ~ 13:00: 스팸 데이터와 일반 대화 데이터를 합치는 등의 데이터 전처리를 마치고 적용할 수 있는 언어 모델을 찾아 적용해보기

22일(토) : 중간 발표를 위한 ppt만들기

**Comment by IamJunhaHwang** [comment]
`10/21`: 모두의 말뭉치 신청 결과가 나오지 않아, 우선 스팸 데이터셋만으로 데이터 전처리를 진행하기로 함.

  - 데이터에 대한 간단한 EDA, 토크나이징 등의 전처리를 하는 방향으로 바꾸기로 함

**Comment by IamJunhaHwang** [comment]
+) **온라인 대화 말뭉치 승인 완료!**

스팸 데이터셋과 함께 진행하면 된다.

**Comment by sdlee130** [comment]
11/05 어플 UI 개발

**Comment by IamJunhaHwang** [comment]
> 11/05 어플 UI 개발

11/04까지 간단하게 안드로이드 스튜디오를 이용해 애뮬레이터에 앱 초기 화면 띄우기 해보기

**Comment by sdlee130** [comment]
> 
앱 초기 화면 띄우기
![image](https://user-images.githubusercontent.com/49019184/199922500-0cd21ab2-794f-4103-9da4-537c1b660e4b.png)

**Comment by sdlee130** [comment]
> > 11/05 어플 UI 개발
> 
> 11/04까지 간단하게 안드로이드 스튜디오를 이용해 애뮬레이터에 앱 초기 화면 띄우기 해보기

![image](https://user-images.githubusercontent.com/49019184/199922662-35a52401-ce26-4a97-a813-0e7a5bf2e79f.png)
앱 초기 화면 띄우기

**Comment by IamJunhaHwang** [comment]
11월 2주차에는 초기 화면을 꾸미고 버튼 배치를 목표로 해보죠. 🔥 

`어도비XD`, `제플린 플러그인`를 사용해보고 해당 사항에 대해 이슈를 적으면 될 것 같아요.

**Comment by IamJunhaHwang** [comment]
### 11월 3주차 개발 일정(모여서)

- `화, 4시 이후`:  앞으로 계획 논의 + 안드로이드 UI 개발

- `금, 오전`: 발명 설명서 초안 작성 

- `토`: 발명 설명서 완성, 발표 준비 & 안드로이드 UI 개발

- `일`: 필요 시 추가 작업
