### ISSUE TITLE
fragment <-> activity 데이터 전달

### ISSUE THREAD

**Issue by sdlee130** [IamJunhaHwang/Anti-S#51]
기능들이 연계되도록 하기 위해 Fragment에서 Mainactivity로 데이터를 전달해야 하는 이슈가 발생하였음.

**Comment by sdlee130** [comment]
현재까지 코드는 fragment와 activity 사이의 데이터 교환은 이루어진 적이 없음.

**Comment by sdlee130** [comment]
기능 연계를 위해서 방법을 찾아봐야겠다.

**Comment by IamJunhaHwang** [comment]
> 기능 연계를 위해서 방법을 찾아봐야겠다.

어떤 기능 연계인가요?

**Comment by sdlee130** [comment]
> > 기능 연계를 위해서 방법을 찾아봐야겠다.
> 
> 어떤 기능 연계인가요?

앱 화면에 나오는 스위치로 SMS 모니터링 기능을 on/off 할 수 있도록 하는 거에요.

**Comment by sdlee130** [comment]
fragment에서 mainactivity 객체를 받아와서 모니터링 기능이 on/off 될 수 있도록 시도 중

**Comment by sdlee130** [comment]
어려움을 겪는 중인데 SMS 모니터링을 막는 것이 아니라 SMS 모니터링을 하여 다음 동작을 하기 전에 on/off 상태를 확인하는 분기를 두는 방법으로라도 구현해봐야겠다.

**Comment by sdlee130** [comment]
> 어려움을 겪는 중인데 SMS 모니터링을 막는 것이 아니라 SMS 모니터링을 하여 다음 동작을 하기 전에 on/off 상태를 확인하는 분기를 두는 방법으로라도 구현해봐야겠다.

굳이 그럴 필요없이 구현을 성공했다.

**Comment by sdlee130** [comment]
> > 어려움을 겪는 중인데 SMS 모니터링을 막는 것이 아니라 SMS 모니터링을 하여 다음 동작을 하기 전에 on/off 상태를 확인하는 분기를 두는 방법으로라도 구현해봐야겠다.
> 
> 굳이 그럴 필요없이 구현을 성공했다.

requireActivity()를 이용하여 activity의 메소드를 fragment에서 사용할 수 있게 해주고 앱 실행시 동적으로 SMS receiver를 한번 등록하게 하여 receiver가 등록되어 있지 않은 IllegalArgumentException를 해결하고 이전에 발생했던 오류도 모두 해결하였다.
