### ISSUE TITLE
마지막 주차 개발 일정

### ISSUE THREAD

**Issue by sdlee130** [IamJunhaHwang/Anti-S#52]
12/05(월) ~ 12/10(토)   
깃허브 관리 마지막 날까지의 개발 일정

**Comment by sdlee130** [comment]
12/05(월)
----------------

- 스미싱 관련 정보 조사하기
- 모델 fine-tune & test

**Comment by sdlee130** [comment]
12/06(화)
----------------

- 스미싱 관련 정보 앱 화면에 띄워주기

- 앱 내에서 메시지 전처리 기능 구현 [코틀린]
  - #16 참고

- 모델 스크립트로 변환

**Comment by sdlee130** [comment]
12/07(수)
----------------

- 수신 메세지 로그 기능 구현하기 
- 모델 HF Hub에 업로드하기

**Comment by sdlee130** [comment]
12/08(목)
----------------

- 수신 메세지 로그 기능 구현하기 
-

**Comment by sdlee130** [comment]
12/09(금)
----------------

- 앱과 모델의 예측 기능 연동하기
- 라이선스 추가

**Comment by sdlee130** [comment]
12/10(토)
----------------

- 앱과 모델의 예측 기능 연동하기
- 최종 점검 [Github 마무리]

**Comment by IamJunhaHwang** [comment]
개발 끝!!! 한 한기 수고수고~ @sdlee130
