### ISSUE TITLE
기말 발표 준비

### ISSUE THREAD

**Issue by sdlee130** [IamJunhaHwang/Anti-S#54]
12/12(월) 14:00에 할 기말 발표에 대한 이슈

**Comment by sdlee130** [comment]
- 필요성
- Problem
- 차별성(or contribution)
- Solution(방법)
- 결과물
  - 계획 대비 결과물의 기능 구현 상황
  - 완성도
    - 완성된 모습(영상, 데모 등)
    - Evaluation(평가) 결과
- Challenging issues, 한계점, 향후 개선방향

**Comment by sdlee130** [comment]
발표시간 7~9분

**Comment by IamJunhaHwang** [comment]
### 계획 대비 결과물의 기능 구현 상황

요구사항분석서와 구현한 기능(화면)을 비교하면서 발표

**Comment by IamJunhaHwang** [comment]
### Evaluation(평가) 결과

모델과 앱 두 가지를 평가 할 예정

- 모델 평가: #21 
- 앱 평가: 기능이 원활하게 실행이 되는가

**Comment by IamJunhaHwang** [comment]
### Challenging issues

- 모델 측면
  - 데이터
  - 모델 서빙..

- 앱 측면
  - mainactivity fragment 사이의 동작을 구현할 때 nullpoiner exception이나 method를 사용할 수 없는 에러가 미숙한 앱 개발로 해결이 오래 걸렸다.

**Comment by IamJunhaHwang** [comment]
### 한계점, 향후 개선방향

- 특수문자로 조합하여 사람이 기호로써 인식할 수 있게 만드는 메시지들

**Comment by IamJunhaHwang** [comment]
위를 고려해서 발표도 잘 준비하도록 하자.
