### ISSUE TITLE
1205 회의록

### ISSUE THREAD

**Issue by sdlee130** [IamJunhaHwang/Anti-S#55]
12/05 16:00 회의 내용 기록 이슈

**Comment by sdlee130** [comment]
현실적으로 가능한 구현목표   
- log 띄워주기
- 모델 적용하기
- 스미싱 신고 방법, 링크 띄워주기

**Comment by sdlee130** [comment]
모여서 함께 진행하는 것은 금, 토에 가능함

**Comment by IamJunhaHwang** [comment]
### 모델 준비 진행 상황

- klue-RoBERTa-small 모델을 학습 완료
  - validation 에서 높은 성능을 보임

  - test set에서 검증해볼 필요 있음.

**Comment by IamJunhaHwang** [comment]
### 모델 개발 앞으로 할 일

- test set으로 검증

- torchscript로 변환한 후 저장하기

- 바꾼 모델을 안드로이드에서 구동되게 만들기

**Comment by sdlee130** [comment]
> 모여서 함께 진행하는 것은 금, 토에 가능함

화요일 오후 시간대에도 가능함

간단한 기능을 화요일에 최대한 구현하는 것으로
