### ISSUE TITLE
메인 스미싱 정보

### ISSUE THREAD

**Issue by sdlee130** [IamJunhaHwang/Anti-S#57]
앱에서 제공하는 스미싱 관련 정보 중에서 가장 중요하다고 생각하는 정보를 정하는 이슈

**Comment by sdlee130** [comment]
@IamJunhaHwang 어떤 정보를 메인으로 띄우는 게 좋을까요?

**Comment by sdlee130** [comment]
- 스미싱 신고 방법
- 스미싱 예방 방법
- 유행했던 스미싱 수법들
- ...

**Comment by IamJunhaHwang** [comment]
> @IamJunhaHwang 어떤 정보를 메인으로 띄우는 게 좋을까요?

유행하는 스미싱 수법들을 먼저 띄우는게 좋을 것 같아요.

**Comment by sdlee130** [comment]
- 간단 스팸/스미싱 신고 방법 -> 불법 스팸 대응 센터에서 알려주는 방법 캡처
- 스미싱 신고 -> 스미싱 신고를 위해 필요한 것을 입력하는 링크
- 스미싱 수법들 -> 불법 스팸 대응 센터의 공지사항에 올라오는 스팸/스미싱 관련 주의사항 링크   

위와 같이 메인 스미싱 정보를 정리 완료하였음으로 이슈는 닫을 게요
