### ISSUE TITLE
모델 서빙 이슈

### ISSUE THREAD

**Issue by IamJunhaHwang** [IamJunhaHwang/Anti-S#58]
모델 서빙 관련해 논의하기 위한 이슈

**Comment by IamJunhaHwang** [comment]
모델을 script로 바꾸어 앱의 프론트 단에서 동작할 수 있도록 계획했었지만 차질이 생겼다.

모델 자체를 `torchsciprt`를 바꿀 수 있지만, 모델에 넣어줄 input을 전처리해줄 tokenizer가 script로 바꿀 수 없는 문제가 있다.

**Comment by IamJunhaHwang** [comment]
따라서, 앱 자체를 Firebase와 연동을 해서 진행하던가 Flask를 이용해 웹 서버를 구축해 동작하게 하는 것을 알아보아야 할 듯한데 어떻게 생각하시나요? @sdlee130

**Comment by IamJunhaHwang** [comment]
- 공식 reference에서는 Tokenzier를 코틀린으로 직접 구현함. 
  - url: https://github.com/pytorch/android-demo-app/tree/master/Seq2SeqNMT/app/src/main

- 우리가 모델을 만들 때 사용했던 토크나이저는 허깅페이스에서 그대로 가져 왔음. [모델을 제공한 KLUE측에서 만든 토크나이저]

- huggingface의 BERT tokenizer: https://github.com/huggingface/transformers/blob/v4.25.1/src/transformers/models/bert/tokenization_bert.py#L137

**Comment by sdlee130** [comment]
> 따라서, 앱 자체를 Firebase와 연동을 해서 진행하던가 Flask를 이용해 웹 서버를 구축해 동작하게 하는 것을 알아보아야 할 듯한데 어떻게 생각하시나요? @sdlee130 

뭐로 하든 차이는 없을 거 같은데 구현할 시간이 될 지 모르겠네요

**Comment by IamJunhaHwang** [comment]
> > 따라서, 앱 자체를 Firebase와 연동을 해서 진행하던가 Flask를 이용해 웹 서버를 구축해 동작하게 하는 것을 알아보아야 할 듯한데 어떻게 생각하시나요? @sdlee130
> 
> 뭐로 하든 차이는 없을 거 같은데 구현할 시간이 될 지 모르겠네요

일단 플라스크를 이용해 간단히 REST API로 구성해보도록 할게요
