### ISSUE TITLE
스팸 데이터셋 전처리에 관한 논의

### ISSUE THREAD

**Issue by sdlee130** [IamJunhaHwang/Anti-S#6]
![image](https://user-images.githubusercontent.com/49019184/194752629-8abacc43-2fb1-4528-a3a6-0c7537eb6052.png)

raw data의 모습

**Comment by sdlee130** [comment]
`스마트 치안 빅데이터 플랫폼`이란 곳에서 한글로 되어 있는 스팸 문자 내용 데이터를 찾았다.

**Comment by IamJunhaHwang** [comment]
`ifg@`는 어떤 것을 의미하는거지??

--------

+) 텍스트 데이터의 패턴을 학습한다는 관점에서는 `[국제발신]`과 같은 부분은 삭제해 주는 것이 좋을 것 같은데?

**Comment by sdlee130** [comment]
`ifg@`가 모든 문자 내용에 들어있는 것을 봤을 때 특정한 특수문자를 대체한 거 같아서 뭐가 있어야 할까를 생각하다가 개행문자 `\n`를 넣고 메모장에 입력해보니 예전에 받아봤던 스팸문자와 형식이 비슷했음.   
데이터를 공개한 페이지에서도 추가 설명은 없어서 일단 개행문자라고 보고 진행해야 할 거 같음.

**Comment by sdlee130** [comment]
숫자가 있어야 할 자리에 `*`문자가 들어있음.

**Comment by IamJunhaHwang** [comment]
데이터의 라이선스는 문제가 없나요??

**Comment by sdlee130** [comment]
사이트에서는 라이센스 관련해서 찾을 수 없었음. 확실히 하려면 더 알아보고 해야할 거 같음.

**Comment by IamJunhaHwang** [comment]
한국어 스팸 데이터를 찾았으니 한국어 정상 대화 데이터에 관한 이슈는 따로 만들어서 기록하도록 하겠습니다.

**Comment by IamJunhaHwang** [comment]
> `ifg@`가 모든 문자 내용에 들어있는 것을 봤을 때 특정한 특수문자를 대체한 거 같아서 뭐가 있어야 할까를 생각하다가 개행문자 `\n`를 넣고 메모장에 입력해보니 예전에 받아봤던 스팸문자와 형식이 비슷했음. 데이터를 공개한 페이지에서도 추가 설명은 없어서 일단 개행문자라고 보고 진행해야 할 거 같음.

`ifg@`의 경우 띄어쓰기로 처리해도 무방할 것 같네요.

그리고 지금 데이터가 너무 raw해서 전처리를 하나씩 해나가면서 데이터를 찍어보면서 진행하는게 어떨까 싶어요.

**Comment by IamJunhaHwang** [comment]
## 스팸 데이터 전처리 [1]

스팸 메시지 데이터 예시 : `FW>ifg@[국제발신]ifg@롤링조건 없음ifg@같이 함께해요ifg@ifg@행운회관.com`

------------

1. 데이터의 경우 머릿말(?)로 `[국제발신]`, `[국외발신]` 이라는 태그가 붙어있다. 모든 메시지에 붙어 있으므로 모델이 스팸을 판단하기 쉬울거라 판단해서 삭제하기로 함.

2. `FW>` 정체 모를 태그... 삭제하기로 함.

3. `ifg@`의 경우 띄어쓰기로 대체하기로 함.

**Comment by IamJunhaHwang** [comment]
## 스팸 데이터 전처리 [2]

- `*` 문자가 광범위하고 무분별하게 들어가 있음.  ==> 삭제하기로 함.

#### 예시
```
처음 **%
삼+삼
**+*
**+**
***+**
그 이상 **%

vⓣ-①⑨④*.com
KEY:***

카톡: pbt**
fst***.com
코드: pbt*
```

**Comment by IamJunhaHwang** [comment]
## 스팸 데이터 전처리 [3]

- 파이썬의 `str.find()` 메소드를 이용해 메시지 안의 url을 시작과 끝 인덱스를 받아와 [URL]토큰으로 바꾸어 줌.

  - url이 문장의 처음과 끝에 등장하는 것을 고려해주어야 했음.

**Comment by IamJunhaHwang** [comment]
## 스팸 데이터 전처리 [4]

- 문자열의 길이가 4이하인 문장 삭제

  - 의미가 없거나 알 수 없는 문장이 되었음. (전처리 후)

**Comment by IamJunhaHwang** [comment]
## 스팸 데이터 전처리 [5]

- 데이터에 영어로만 이루어진 텍스트도 있어서 전처리 후에는 특수문자만 남게 되었음.

- 따라서, 전처리 전에 영어 텍스트의 경우 drop 해주는 메소드 생성

  - 문장 내에서 알파벳이 알파벳이외의 문자보다 많을 시 영어 문장으로 판단

**Comment by IamJunhaHwang** [comment]
## 스팸 데이터 전처리 [6]

- 스팸 데이터의 경우 레이블 값을 `1`로 처리

**Comment by IamJunhaHwang** [comment]
## 스팸 데이터 전처리 [7]

- Max_len = 128로 설정.

  - SMS의 최대 작성 가능한 길이는 75자

  - 단 MMS로 수신 시 최대 작성 가능한 길이 제한이 없어짐. (후에 다뤄보아야 할 이슈)

**Comment by IamJunhaHwang** [comment]
### 현재까지는 위의 전처리로 fix하기로 함.  이렇게 이번 이슈는 닫고 추후 논의 사항이 생겼을 때 다시 이슈를 생성하도록 하자.
