### ISSUE TITLE
정상 대화 데이터셋 전처리에 관한 논의

### ISSUE THREAD

**Issue by IamJunhaHwang** [IamJunhaHwang/Anti-S#7]
정상 대화 데이터셋에 관한 논의를 위한 이슈입니다.

첫 단계로는 정상 대화 데이터셋을 어떤 것을 사용할지 채택하여야 되는데 모두의 말뭉치에 한국어 대화 데이터셋이 두 개 있어 이 중 하나를 고르면 될 것 같습니다.

**Comment by sdlee130** [comment]
두 말뭉치가 어떤 차이가 있나요?

**Comment by IamJunhaHwang** [comment]
말뭉치 정보입니다.

**A. 온라인 대화 말뭉치**
- 설명: 두  명  이상의  대화  참여자가  온라인  공간에서  주고받은  대화  자료를  대상으로  구축한  말뭉치 ,  대화  참여자들의  자연스러운  언어  습관이  그대로  반영되어  있으며 개인  정보  등은  비식별화 처리함

- 분량: 총  74,665건 (메시지 3,069,927  개)

**B. 메신저 말뭉치**

- 설명: 두  명  이상의  대화  참여자가  메신저로  나눈  메신저  대화  자료,  대화  참여자들의  자연스러운  언어  습관이  그대로  반영되어  있으며 개인  정보  등은  비식별화 처리함.

-   분량: 3,836건 (메시지 691,535 개) 

-------

- 안의 내용은 비슷해보입니다.

- 예시 내용이어도 이 곳에 캡처해서 남기는 것은 문제가 될 수 있으니 아래 사이트에서 설명 자료를 내려받아 확인하면 좋을 것 같습니다.

https://corpus.korean.go.kr/request/corpusRegist.do

**Comment by sdlee130** [comment]
정상 대화 데이터셋은 공개되지 않도록 주의할 것

**Comment by sdlee130** [comment]
특수 메시지
- 이모티콘 {emoji}
- 선물하기 {system: gift}
- 통화 {system: call}
- 송금 {system: money}
- 공지 {system: notice}
- 지도 공유 {system: map}
- 연락처 공유 {system: contact}
- 메시지 삭제 {system: delete}
- 사진 공유 {share: photo}
- 동영상 공유 {share: video}
- 음악 공유 {share: music}
- 파일 공유 {share: file}
- 음성 메시지 공유 {share: voice}
- 정보 공유 {share: info}
- URL 공유 {share: url}
- 부적절 대화 {censored}

**Comment by sdlee130** [comment]
비식별화 기호
- 이름 &name&
- 온라인 계정 &account&
- 고유 식별 번호 &social-security-num&
- 전화번호 &tel-num&
- 금융 번호 &card-num&
- 기타 번호 &num&
- 주소 &address&
- 출신, 소속 &affiliation&
- 기타 &others&

**Comment by sdlee130** [comment]
위의 비식별화 기호와 특수 메시지 중 URL 공유 태그를 제외하고는 모두 지웠다.   
문장에 개행문자 "\r\n"는 공백 문자 " "로 치환하였다.

**Comment by sdlee130** [comment]
여기까지 했을 때 [URL]태그만 남아있는 문장이 있었는데 이것은 없애기로 결정하였다.

**Comment by sdlee130** [comment]
문자열 길이가 4 이하인 것은 너무 짧은 문장이라 제거하였다.

**Comment by sdlee130** [comment]
정상 데이터셋은 0 값으로 Label column을 추가하였다.

**Comment by sdlee130** [comment]
비정상 데이터셋과 데이터량의 비율을 5대5로 맞추기 위해 난수로 26816개의 행을 뽑아서 chat_part로 만들었다.

**Comment by sdlee130** [comment]
난수로 뽑기전에 URL이 있는 문장을 우선적으로 뽑아낸 후 샘플링 진행하였다.
