### ISSUE TITLE
22.10.17 회의록

### ISSUE THREAD

**Issue by IamJunhaHwang** [IamJunhaHwang/Anti-S#8]
2022.10.17.에 진행된 회의 내용을 기록하기 위한 이슈입니다.

**Comment by sdlee130** [comment]
18일 화 16:00부터 18:00까지   
+   
19일 수 13:00부터 16:00까지   
이 시간 활용해서 요구사항 정의서를 완성시켜보도록 하자.

**Comment by IamJunhaHwang** [comment]
요구사항 정의서의 경우, 기존 초안을 더욱 디테일하게 수정하는 것을 목표로 합시다. (특히 기능적 요구사항 부분)

**Comment by IamJunhaHwang** [comment]
요구사항 정의서의 경우 멘토링 시간에 조언을 받은 내용이므로 이 부분을 발표 자료에 넣어야 한다. 따라서, before/after 비교 등과 같이 발표 때 어떻게 사용할지도 생각하면서 하도록 하자.

**Comment by sdlee130** [comment]
20일 10:00부터 13:00까지   
+   
21일 10:00부터 13:00까지   
   
목표: 스팸 데이터와 일반 대화 데이터를 합치는 등의 데이터 전처리를 마치고 적용할 수 있는 언어모델을 찾아 적용해보기

**Comment by sdlee130** [comment]
위에 제시한 시간 외에도 가능하다면 저녁 시간까지도 활용할 필요가 있음

**Comment by sdlee130** [comment]
22일 13:00부터 18:00까지   
   
목표: 중간 발표를 위한 ppt만들기

**Comment by sdlee130** [comment]
ppt는 발표 전까지는 디테일은 수정 가능하니 전체적인 스토리 라인을 위주로 만들면 될 거 같음

**Comment by sdlee130** [comment]
> 요구사항 정의서의 경우 멘토링 시간에 조언을 받은 내용이므로 이 부분을 발표 자료에 넣어야 한다. 따라서, before/after 비교 등과 같이 발표 때 어떻게 사용할지도 생각하면서 하도록 하자.

용어 정의 관련해서도 누가 읽어도 이해할 수 있도록 전공 관련 용어들은 정의를 해주자

**Comment by IamJunhaHwang** [comment]
개발 일정 관련은 #5 이슈에 정리해서 옮기고, 발표 관련 이슈를 새로 생성해서 논의를 이어 나가는게 좋을 것 같네요.

해당 이슈는 close 하겠습니다.
