### ISSUE TITLE
중간 발표 자료 준비 논의

### ISSUE THREAD

**Issue by IamJunhaHwang** [IamJunhaHwang/Anti-S#9]
### 포함되어야 하는 내용

- 필요성
  - problem을 왜 풀어야 하는지, 왜 중요한지

- Problem 정의
  - input/output 명시
  
- 차별성(or Contribution)

- 방법
  - 제안하는 방법, 모델, 구현방향 등
  - 현재까지의 구현 상황
  
- 멘토링 결과에 대한 적용
  - 우리의 경우 `요구사항정의서`

- Optional
  - 개발 일정
  - Evaluation Plan

- **주의! 발표 시간을 잘 안배해야 됨!**

**Comment by IamJunhaHwang** [comment]
### 필요성 정의에 최근에 있었던 일을 넣으면 임팩트 있을 것 같아요!

https://www.segye.com/newsView/20221017517952?OutUrl=naver

데이터센터 화재로 인해 카카오톡이 먹통이 되면서 스미싱 유포로 안전 안내 문자 등으로 과기정통부에서 주의시켰다는 내용입니다.

**Comment by IamJunhaHwang** [comment]
### Baseline 모델 정보

https://huggingface.co/tunib/electra-ko-base

https://tunib.tistory.com/entry/TUNiB-Electra-%EA%B3%B5%EA%B0%9C

- TUNIB AI 에서 공개한 Ko-Electra

- Huggingface 라이브러리를 이용해 바로 사용할 수 있음

**Comment by IamJunhaHwang** [comment]
### Evaluation Plan

모델 평가에 대해 작성하면 될 것 같음. 일단 생각한 내용은 아래와 같음.

- `KLUE` 데이터의 Topic Classification Task를 이용
- 네이버 영화 리뷰 데이터셋 이용.

- 평가 메트릭: F1-score와 Recall을 확인하는 것으로 결정.

  - 스미싱 위협이 감지되는 민감도를 올리는 것을 목표로 하기로 정함.

**Comment by sdlee130** [comment]
발표 최종 점검은 10/24(월) 13:00 - 14:00에 하도록 합시다.
